service: authorization-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

resources:
  Outputs:
    BasicAuthorizerArn:
      Value: !GetAtt
        - BasicAuthorizerLambdaFunction
        - Arn
      Export:
        Name: BasicAuthorizerArn

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer

