service: import-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

  environment:
    CATALOG_ITEMS_QUEUE_URL:
      Fn::ImportValue: product-service-catalog-items-queue-url

  iamRoleStatements:
    - Effect: 'Allow'
      Action: 's3:ListBucket'
      Resource:
        - 'arn:aws:s3:::nodejs-aws-be-upload'
    - Effect: 'Allow'
      Action: 's3:*'
      Resource:
        - 'arn:aws:s3:::nodejs-aws-be-upload/*'
    - Effect: 'Allow'
      Action: 'sqs:*'
      Resource:
        Fn::ImportValue: product-service-catalog-items-queue-arn
#          - Fn::GetAtt: [ CatalogItemsQueue, Arn ]
#        - "${cf:product-service-${self:provider.stage}.SQSQueueArn}"

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: nodejs-aws-be-upload
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

